- src/js/categories/categories.js
- src/js/categories/fetchBooks.js
- src/partials/categories.html
- src/sass/categories.scss
Added base render categories branch books gallery
> Added base render categories branch books gallery

- src/js/categories/categories.js
- src/partials/categories.html
- src/sass/categories.scss
Added separated styles to title;
Updated class list;
> Categories page

- src/js/categories/categories.js
- src/sass/categories.scss
Updated styles scc to mobile/tab/desc
> Updated styles scc to mobile/tab/desc

- src/partials/categories.html
- src/sass/categories.scss
> Categories container

- src/js/categories/categories.js
- src/partials/categories.html
- src/sass/categories.scss
Added hover + focus to book cards
> Added hover + focus to book cards

- src/js/best-sellers/best-sellers.js
- src/js/best-sellers/fetchTopBooks.js
- src/sass/best-sellers.scss
> add js/base css

- src/js/best-sellers/best-sellers.js
- src/js/categories/categories.js
Додано виклик функції рендеру бестселлеру до лінка All categories;
Додано виклик функції рендеру категорії до кнопок
> Categories

- src/index.html
- src/js/categories/categories.js
- src/partials/categories.html
- src/sass/categories.scss
Included support-ukraine to categories
> Included support-ukraine to categories

- src/js/best-sellers/best-sellers.js
> Added data-id

- src/js/best-sellers/best-sellers.js
- src/js/categories/categories.js
- src/partials/categories.html
Added ul to render top list books
> Added ul to render top list books

- src/sass/best-sellers.scss
> Fixed button styles

- src/js/categories/categories.js
> Updated loader function

- src/sass/best-sellers.scss
> Updated styles

- src/partials/support-ukraine.html
- src/sass/support-ukraine.scss
> support-Ukraine-09052023-css

- src/sass/categories.scss
> Update tab styles

- src/js/best-sellers/best-sellers.js
> Added "resize" listener

- package-lock.json
- package.json
- src/js/best-sellers/best-sellers.js
- src/js/support-ukraine/support-ukraine.js
> Added lodash.debounce

- src/js/best-sellers/best-sellers.js
> Updated debounce

- src/js/categories/categories.js
Updated categories list active class (btn click)
> Updated categories list active class (btn click)

- src/js/best-sellers/best-sellers.js
- src/sass/best-sellers.scss
> Added hover/focus to btn

- src/sass/best-sellers.scss
- src/sass/categories.scss
Updated animation with variables
> Updated animation with variables

- src/sass/book-modal.scss
fixed dark theme in book modal
> book modal

- src/sass/base.scss
> shopping list

- src/js/best-sellers/best-sellers.js
- src/sass/best-sellers.scss
> Fixed flex styles

- src/js/authorization/sign-in-sign-up.js
> authorization

- src/js/shopping-list/shopping-list.js
- src/shopping-list.html
> Added Loader to shopping list

- src/index.html
- src/sass/support-ukraine.scss
- src/shopping-list.html
index.html & shoppingList.html
change from ru to en
> fixes css by support-Ukraine

- src/js/best-sellers/best-sellers.js
- src/js/book-modal/book-modal.js
> Update if title.text
